import = [
    # "~/.config/alacritty/catppuccin-latte.toml"
    "~/.config/alacritty/catppuccin-frappe.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "MesloLGL Nerd Font"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 1.0

[window.padding]
x = 6
y = 0

[scrolling]
history = 10000
