import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "MesloLGL Nerd Font"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 1.0
decorations = "buttonless"

[window.padding]
x = 6
y = 0

[scrolling]
history = 10000
